### PR TITLE
consumer: backoff strategies

### PR DESCRIPTION
**Pull request by mreiferson**
refactoring of the work in #123

RFR @jehiah

### CODE REVIEW

**Comment by jehiah** [comment]
code looks good (Aside from integration test failures)

**Comment by mreiferson** [comment]
updated

**Comment by jehiah** [comment]
LGTM

**Comment by mreiferson** [comment]
:hammer:

**Comment by twmb** [comment]
It nice be beneficial to document that the code calls `setConfig` so that implementors can also use the function, the same way `flag` does `IsBoolFlag`.

**Comment by mreiferson** [comment]
@twmb I made those explicitly private, I don't want others relying on that method/interface/etc.  My expectation is that user-implemented `BackoffStrategy` would use their own parameters/config.

**Pull request merged**
