### PR TITLE
Consumer stall after RequeueWithoutBackoff

### PR DESCRIPTION
**Pull request by jehiah**
If a consumer is in backoff and attempts to recover with RDY 1 and then a message, but response with RequeueWithoutBackoff it will stall and not exit backoff. (failing test attached)

cc: @georgicodes

### CODE REVIEW

**Comment by mreiferson** [comment]
:fire:

**Comment by jehiah** [comment]
RFR @mreiferson

**Comment by mreiferson** [comment]
I'm not following the need for https://github.com/jehiah/go-nsq/commit/f0be171099c3f2b7a264cabb8fb0447a21d60529

**Comment by jehiah** [comment]
I moved the lock so that it covered both the `r.inBackoffBlock()` check on line 648 and the updating of backoffDuration which is set on line 692. Without that spanning both i suspect there is a race condition in startStopContinueBackoff. (though to be honest i just noticed this reading the code; there could be other factors that keep that from not being an issue).

As i read it, that potential race could allow simultaneous finishes on more than one message/connection (this is fed by per-connection goroutines) to update rdy and backoff unexpectedly.

**Comment by mreiferson** [comment]
@jehiah that's `atomic` though?  The only thing it needs to protect is `backoffCounter`... Let's remove that commit?

**Comment by jehiah** [comment]
Yes, backoffCounter updates need to be protected, but that update also needs to also include the check and update for `inBackoffBlock` or it will be possible to have it executed multiple times (sequentially) in the same backoff time period. 

ie: pathalogical current case is you have 10 messages on different connections req to trigger backoff; they all pass the `inBackoffBlock` and then sequentially (because of the current lock) each update backoffCounter. We want only one of those to proceed past the `inBackoffBlock` check and update the counter. The first message that passes should prevent any other message (ie: by the lock also encompassing the update to `backoffDuration`).

**Comment by mreiferson** [comment]
Ahh, I thought you meant a "data" race.

Gonna read through again, thanks for the info...

**Comment by mreiferson** [comment]
OK - I think you're right, nice catch.

While I was reading the code I cleaned up some other related things (pushed here).

My suggestion is - can't we use `atomic` ops for `backoffCounter`?  This would mean that `backoffMtx` is more clearly _only_ used to serialize execution of `startStopContinueBackoff`.

**Comment by mreiferson** [comment]
(I'm going to give that a try)

**Comment by mreiferson** [comment]
@jehiah check those

**Comment by jehiah** [comment]
@mreiferson changes look good. two more small tweaks pushed. If you are good i'll squash this down.

**Comment by mreiferson** [comment]
:+1: :hammer:

**Comment by mreiferson** [comment]
P.S. bump go versions in travis too?

**Comment by twmb** [comment]
Does backoff with a MaxBackoffDuration of 0 not race with resume?

The `time.AfterFunc` in `backoff` will immediately try to call resume, randomly picking a connection to `updateRDY(1)`, while `backoff` is still finishing trying to `updateRDY(0)` for all connections.

I might be reading it wrong, though; I've not yet finished reading all of conn/consumer/delegates to see how it *all* fits together.

**Comment by mreiferson** [comment]
@twmb Nice catch, I think you're right.  @jehiah We need to reorder those operations (and we shouldn't send rdy 0 anyway if the calculated duration is 0.

**Comment by twmb** [comment]
Not sending `RDY 0` if backoff duration is 0 is another way of addressing #129.

**Pull request merged**
