### PR TITLE
consumer: jitter might have no effect

### PR DESCRIPTION
**Pull request by judwhite**
please review if this is correct behavior

### CODE REVIEW

**Comment by mreiferson** [comment]
Can you explain these changes? Not sure this is desirable...

**Comment by judwhite** [comment]
ticker starts when it's created. when it's created before waiting on jitter the jitter has no effect, unless jitter is greater than the tick interval.

example:

	start := time.Now()

	ticker := time.NewTicker(1500 * time.Millisecond)
	time.Sleep(1000 * time.Millisecond)

	<-ticker.C

	fmt.Println(time.Now().Sub(start))

**Comment by mreiferson** [comment]
ahh, that makes more sense :+1:, really nice catch!

**Comment by mreiferson** [comment]
mind squashing down?  thanks for this...

**Comment by judwhite** [comment]
reopened as https://github.com/bitly/go-nsq/pull/114

**Pull request closed without merging**
