### PR TITLE
fix maxBackoffDuration

### PR DESCRIPTION
**Pull request by hankya**
Please refer to https://github.com/bitly/go-nsq/pull/142

### CODE REVIEW

**Comment by mreiferson** [comment]
@hankya I think we need to add this code back around here:

https://github.com/bitly/go-nsq/blob/master/consumer.go#L797

**Comment by hankya** [comment]
Right, it should have been added:)

I've just added another commit for this, please check it out.

**Comment by mreiferson** [comment]
@hankya looks good - would you mind squashing your commits down to one?  You can do this in the same branch on this PR, just force push after you've squashed.

**Comment by mreiferson** [comment]
see #147

**Pull request closed without merging**
